"""Add_booking_notification_table

Revision ID: dc04d9e712dd
Revises: 6e0a83780971
Create Date: 2026-08-26 11:49:56.343532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc04d9e712dd'
down_revision: Union[str, Sequence[str], None] = '6e0a83780971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_notifications',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REMINDER_CLIENT', 'CREATED', 'UPDATED', 'CANCELED', name='booking_notification_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELED', name='booking_notification_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='check_attempts_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_booking_id_booking_notifications', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_notifications_booking_id'), 'booking_notifications', ['booking_id'], unique=False)
    op.create_index('ix_booking_notifications_pending_due', 'booking_notifications', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_booking_notifications_stuck_recovery', 'booking_notifications', ['updated_at'], unique=False, postgresql_where=sa.text("status = 'PROCESSING'"))
    op.create_index('unique_booking_notifications_booking_type', 'booking_notifications', ['booking_id', 'type'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELED', 'FAILED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_booking_notifications_booking_type', table_name='booking_notifications', postgresql_where=sa.text("status NOT IN ('CANCELED', 'FAILED')"))
    op.drop_index('ix_booking_notifications_stuck_recovery', table_name='booking_notifications', postgresql_where=sa.text("status = 'PROCESSING'"))
    op.drop_index('ix_booking_notifications_pending_due', table_name='booking_notifications', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_booking_notifications_booking_id'), table_name='booking_notifications')
    op.drop_table('booking_notifications')
    # ### end Alembic commands ###
