"""Add_uq_slot_cafe_start_end_into_slots

Revision ID: cb23dce39683
Revises: b7c8d9e0f1a2
Create Date: 2026-09-02 23:07:23.900626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb23dce39683'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_slot_cafe_start_end', 'slots', ['cafe_id', 'start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_slot_cafe_start_end', 'slots', type_='unique')
    # ### end Alembic commands ###
