"""add_uniq_active_booking_table_slot_index

Revision ID: 199a233798f4
Revises: cb23dce39683
Create Date: 2026-09-05 10:42:18.626780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199a233798f4'
down_revision: Union[str, Sequence[str], None] = 'cb23dce39683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uniq_active_booking_table_slot', 'bookingtableslots', ['table_id', 'slot_id'], unique=True, postgresql_where='is_active = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_active_booking_table_slot', table_name='bookingtableslots', postgresql_where='is_active = true')
    # ### end Alembic commands ###
