services:
  app:
    build: ../.devcontainer
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  celery-worker:
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/src

  flower:
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/src
