COMMON_DESCRIPTION_MAX_LENGTH = 500
COMMON_MIN_LENGTH = 1
PHONE_NUMBER_MAX_LENGTH = 20

ACTION_DESCRIPTION_MAX_LENGTH = 1000
BOOKING_NOTE_MAX_LENGTH = 500
CAFE_NAME_MAX_LENGTH = 150
CAFE_ADDRESS_MAX_LENGTH = 255
DISH_NAME_MAX_LENGTH = 100
DISH_PRICE_GT = 0
DISH_PRICE_MAX_DIGITS = 10
DISH_PRICE_DECIMAL_PLACES = 2
USER_USERNAME_MAX_LENGTH = 64
USER_EMAIL_MAX_LENGTH = 255
USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 255
USER_TG_ID_MAX_LENGTH = 64
AUTH_DATA_LOGIN_MAX_LENGTH = 320
MIN_STR_LNGH = 1

MAX_NOTIFICATION_ATTEMPTS = 3
NOTIFICATION_ERROR_MAX_LENGTH = 1024
